openapi: 3.0.0
info:
  title: Blogript API
  description: Blogript API Docs
  version: "1.0.0"
#servers:
  #- url:

paths:
  /blog:
    get:
      summary: Get all posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

    post:
      summary: Create a new post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Posting'
      responses:
        '201':
          description: Post created successfully

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
        author:
          type: string
        content:
          type: string
        creation_date:
          type: date
    Posting:
      type: object
      properties:
        user_id:
          type: UUID
        content:
          type: string